/**
 * Copyright (c) 2014 Microsoft Open Technologies, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 *    Microsoft would like to thank the following companies for their review and
 *    assistance with these files: Intel Corporation, Mellanox Technologies Ltd,
 *    Dell Products, L.P., Facebook, Inc., Marvell International Ltd.
 *
 * AUTOGENERATED FILE! DO NOT EDIT
 *
 * Copyright (c) 2021 Alibaba Group.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 * @file    saiexperimentalotaiotdr.h
 *
 * @brief   This module defines the OTDR for the OTAI
 */

#if !defined (__SAIEXPERIMENTALOTAIOTDR_H_)
#define __SAIEXPERIMENTALOTAIOTDR_H_

#include <saitypes.h>

/**
 * @defgroup SAIEXPERIMENTALOTAIOTDR SAI - OTAI OTDR specific API definitions
 *
 * @{
 */

/**
 * @brief OTDR attribute IDs
 */
typedef enum _sai_otai_otdr_attr_t
{
    /**
     * @brief Start of attributes
     */
    SAI_OTAI_OTDR_ATTR_START,

    /**
     * @brief Id
     *
     * @type sai_uint32_t
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
     */
    SAI_OTAI_OTDR_ATTR_ID = SAI_OTAI_OTDR_ATTR_START,

    /**
     * @brief Refractive index
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_REFRACTIVE_INDEX,

    /**
     * @brief Backscatter index
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_BACKSCATTER_INDEX,

    /**
     * @brief Reflection threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_REFLECTION_THRESHOLD,

    /**
     * @brief Splice loss threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_SPLICE_LOSS_THRESHOLD,

    /**
     * @brief End of fiber threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_END_OF_FIBER_THRESHOLD,

    /**
     * @brief Distance range
     *
     * @type sai_uint32_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_DISTANCE_RANGE,

    /**
     * @brief Pulse width
     *
     * @type sai_uint32_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_PULSE_WIDTH,

    /**
     * @brief Average time
     *
     * @type sai_uint32_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_AVERAGE_TIME,

    /**
     * @brief Output frequency
     *
     * @type sai_uint64_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_OUTPUT_FREQUENCY,

    /**
     * @brief Enabled
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_ENABLED,

    /**
     * @brief Scan
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_SCAN,

    /**
     * @brief Start time
     *
     * @type char
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_START_TIME,

    /**
     * @brief Period
     *
     * @type sai_uint32_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OTDR_ATTR_PERIOD,

    /**
     * @brief Dynamic range
     *
     * @type sai_uint32_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_DYNAMIC_RANGE,

    /**
     * @brief Distance accuracy
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_DISTANCE_ACCURACY,

    /**
     * @brief Sampling resolution
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_SAMPLING_RESOLUTION,

    /**
     * @brief Loss dead zone
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_LOSS_DEAD_ZONE,

    /**
     * @brief Reflection dead zone
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_REFLECTION_DEAD_ZONE,

    /**
     * @brief Scanning status
     *
     * @type sai_uint32_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OTDR_ATTR_SCANNING_STATUS,

    /**
     * @brief End of attributes
     */
    SAI_OTAI_OTDR_ATTR_END,

    /** Custom range base value */
    SAI_OTAI_OTDR_ATTR_CUSTOM_RANGE_START = 0x10000000,

    /** End of custom range base */
    SAI_OTAI_OTDR_ATTR_CUSTOM_RANGE_END

} sai_otai_otdr_attr_t;

/**
 * @brief OTDR stat IDs
 */
typedef enum _sai_otai_otdr_stat_t
{
    /**
     * @brief Start of statistics
     */
    SAI_OTAI_OTDR_STAT_START,

    /**
     * @brief A placeholder
     */
    SAI_OTAI_OTDR_STAT_NOT_USE = SAI_OTAI_OTDR_STAT_START,

    /**
     * @brief End of statistics
     */
    SAI_OTAI_OTDR_STAT_END,

} sai_otai_otdr_stat_t;

/**
 * @brief Create OTDR.
 *
 * Allocates and initializes a OTDR.
 *
 * @param[out] otai_otdr_id OTDR id
 * @param[in] switch_id Switch id on which the OTDR exists
 * @param[in] attr_count Number of attributes
 * @param[in] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_create_otai_otdr_fn)(
        _Out_ sai_object_id_t *otai_otdr_id,
        _In_ sai_object_id_t switch_id,
        _In_ uint32_t attr_count,
        _In_ const sai_attribute_t *attr_list);

/**
 * @brief Remove OTDR
 *
 * @param[in] otai_otdr_id OTDR id
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_remove_otai_otdr_fn)(
        _In_ sai_object_id_t otai_otdr_id);

/**
 * @brief Set OTDR attribute
 *
 * @param[in] otai_otdr_id OTDR id
 * @param[in] attr Attribute
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_set_otai_otdr_attribute_fn)(
        _In_ sai_object_id_t otai_otdr_id,
        _In_ const sai_attribute_t *attr);

/**
 * @brief Get OTDR attribute
 *
 * @param[in] otai_otdr_id OTDR id
 * @param[in] attr_count Number of attributes
 * @param[inout] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_otdr_attribute_fn)(
        _In_ sai_object_id_t otai_otdr_id,
        _In_ uint32_t attr_count,
        _Inout_ sai_attribute_t *attr_list);

/**
 * @brief Get OTDR statistics.
 *
 * @param[in] otai_otdr_id OTDR id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_otdr_stats_fn)(
        _In_ sai_object_id_t otai_otdr_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _Out_ uint64_t *counters);

/**
 * @brief Get OTDR statistics extended.
 *
 * @param[in] otai_otdr_id OTDR id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[in] mode Statistics mode
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_otdr_stats_ext_fn)(
        _In_ sai_object_id_t otai_otdr_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _In_ sai_stats_mode_t mode,
        _Out_ uint64_t *counters);

/**
 * @brief Clear OTDR statistics counters.
 *
 * @param[in] otai_otdr_id OTDR id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_clear_otai_otdr_stats_fn)(
        _In_ sai_object_id_t otai_otdr_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids);

/**
 * @brief Routing interface methods table retrieved with sai_api_query()
 */
typedef struct _sai_otai_otdr_api_t
{
    sai_create_otai_otdr_fn                create_otai_otdr;
    sai_remove_otai_otdr_fn                remove_otai_otdr;
    sai_set_otai_otdr_attribute_fn         set_otai_otdr_attribute;
    sai_get_otai_otdr_attribute_fn         get_otai_otdr_attribute;
    sai_get_otai_otdr_stats_fn             get_otai_otdr_stats;
    sai_get_otai_otdr_stats_ext_fn         get_otai_otdr_stats_ext;
    sai_clear_otai_otdr_stats_fn           clear_otai_otdr_stats;
} sai_otai_otdr_api_t;

/**
 * @}
 */
#endif /** __SAIEXPERIMENTALOTAIOTDR_H_ */
