/**
 * Copyright (c) 2014 Microsoft Open Technologies, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 *    Microsoft would like to thank the following companies for their review and
 *    assistance with these files: Intel Corporation, Mellanox Technologies Ltd,
 *    Dell Products, L.P., Facebook, Inc., Marvell International Ltd.
 *
 * AUTOGENERATED FILE! DO NOT EDIT
 *
 * Copyright (c) 2021 Alibaba Group.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 * @file    saiexperimentalotaioa.h
 *
 * @brief   This module defines the OA for the OTAI
 */

#if !defined (__SAIEXPERIMENTALOTAIOA_H_)
#define __SAIEXPERIMENTALOTAIOA_H_

#include <saitypes.h>

/**
 * @defgroup SAIEXPERIMENTALOTAIOA SAI - OTAI OA specific API definitions
 *
 * @{
 */

/** @brief OA type */
typedef enum _sai_otai_oa_type_t
{
    SAI_OTAI_OA_TYPE_EDFA,
    SAI_OTAI_OA_TYPE_FORWARD_RAMAN,
    SAI_OTAI_OA_TYPE_BACKWARD_RAMAN,
    SAI_OTAI_OA_TYPE_HYBRID,
} sai_otai_oa_type_t;

/** @brief OA gain range */
typedef enum _sai_otai_oa_gain_range_t
{
    SAI_OTAI_OA_GAIN_RANGE_LOW_GAIN_RANGE,
    SAI_OTAI_OA_GAIN_RANGE_MID_GAIN_RANGE,
    SAI_OTAI_OA_GAIN_RANGE_HIGH_GAIN_RANGE,
    SAI_OTAI_OA_GAIN_RANGE_FIXED_GAIN_RANGE,
} sai_otai_oa_gain_range_t;

/** @brief OA amp mode */
typedef enum _sai_otai_oa_amp_mode_t
{
    SAI_OTAI_OA_AMP_MODE_CONSTANT_POWER,
    SAI_OTAI_OA_AMP_MODE_CONSTANT_GAIN,
    SAI_OTAI_OA_AMP_MODE_DYNAMIC_GAIN,
    SAI_OTAI_OA_AMP_MODE_DYNAMIC_POWER,
} sai_otai_oa_amp_mode_t;

/** @brief OA fiber type profile */
typedef enum _sai_otai_oa_fiber_type_profile_t
{
    SAI_OTAI_OA_FIBER_TYPE_PROFILE_DSF,
    SAI_OTAI_OA_FIBER_TYPE_PROFILE_LEAF,
    SAI_OTAI_OA_FIBER_TYPE_PROFILE_SSMF,
    SAI_OTAI_OA_FIBER_TYPE_PROFILE_TWC,
    SAI_OTAI_OA_FIBER_TYPE_PROFILE_TWRS,
} sai_otai_oa_fiber_type_profile_t;

/** @brief OA working state */
typedef enum _sai_otai_oa_working_state_t
{
    SAI_OTAI_OA_WORKING_STATE_LOS_A,
    SAI_OTAI_OA_WORKING_STATE_LOS_N,
} sai_otai_oa_working_state_t;

/**
 * @brief OA attribute IDs
 */
typedef enum _sai_otai_oa_attr_t
{
    /**
     * @brief Start of attributes
     */
    SAI_OTAI_OA_ATTR_START,

    /**
     * @brief ID
     *
     * @type sai_uint32_t
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
     */
    SAI_OTAI_OA_ATTR_ID = SAI_OTAI_OA_ATTR_START,

    /**
     * @brief Type
     *
     * @type sai_otai_oa_type_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OA_ATTR_TYPE,

    /**
     * @brief Target gain
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_TARGET_GAIN,

    /**
     * @brief Min gain
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OA_ATTR_MIN_GAIN,

    /**
     * @brief Max gain
     *
     * @type sai_double_t
     * @flags READ_ONLY
     */
    SAI_OTAI_OA_ATTR_MAX_GAIN,

    /**
     * @brief Target gain tilt
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_TARGET_GAIN_TILT,

    /**
     * @brief Gain range
     *
     * @type sai_otai_oa_gain_range_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_GAIN_RANGE,

    /**
     * @brief Amp mode
     *
     * @type sai_otai_oa_amp_mode_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_AMP_MODE,

    /**
     * @brief Target output power
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_TARGET_OUTPUT_POWER,

    /**
     * @brief Max output power
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_MAX_OUTPUT_POWER,

    /**
     * @brief Enabled
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_ENABLED,

    /**
     * @brief Fiber type profile
     *
     * @type sai_otai_oa_fiber_type_profile_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_FIBER_TYPE_PROFILE,

    /**
     * @brief Ingress port
     *
     * @type char
     * @flags READ_ONLY
     */
    SAI_OTAI_OA_ATTR_INGRESS_PORT,

    /**
     * @brief Egress port
     *
     * @type char
     * @flags READ_ONLY
     */
    SAI_OTAI_OA_ATTR_EGRESS_PORT,

    /**
     * @brief Working state
     *
     * @type sai_otai_oa_working_state_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_WORKING_STATE,

    /**
     * @brief Input LOS threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_INPUT_LOS_THRESHOLD,

    /**
     * @brief Input LOS hysteresis
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_INPUT_LOS_HYSTERESIS,

    /**
     * @brief Output LOS threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_OUTPUT_LOS_THRESHOLD,

    /**
     * @brief Output LOS hysteresis
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_OUTPUT_LOS_HYSTERESIS,

    /**
     * @brief Gain low threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_GAIN_LOW_THRESHOLD,

    /**
     * @brief Gain low hysteresis
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_GAIN_LOW_HYSTERESIS,

    /**
     * @brief Input low threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_INPUT_LOW_THRESHOLD,

    /**
     * @brief Output low threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_OUTPUT_LOW_THRESHOLD,

    /**
     * @brief Enable APR node
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_APR_NODE_ENABLE,

    /**
     * @brief APR node reflection threshold
     *
     * @type sai_double_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_APR_NODE_REFLECTION_THRESHOLD,

    /**
     * @brief Enable APR line
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OA_ATTR_APR_LINE_ENABLE,

    /**
     * @brief End of attributes
     */
    SAI_OTAI_OA_ATTR_END,

    /** Custom range base value */
    SAI_OTAI_OA_ATTR_CUSTOM_RANGE_START = 0x10000000,

    /** End of custom range base */
    SAI_OTAI_OA_ATTR_CUSTOM_RANGE_END

} sai_otai_oa_attr_t;

/**
 * @brief OA stat IDs
 */
typedef enum _sai_otai_oa_stat_t
{
    /**
     * @brief Start of statistics
     */
    SAI_OTAI_OA_STAT_START,

    /**
     * @brief Temperature
     */
    SAI_OTAI_OA_STAT_TEMPERATURE = SAI_OTAI_OA_STAT_START,

    /**
     * @brief Actual gain
     */
    SAI_OTAI_OA_STAT_ACTUAL_GAIN,

    /**
     * @brief Actual gain tilt
     */
    SAI_OTAI_OA_STAT_ACTUAL_GAIN_TILT,

    /**
     * @brief Input power total
     */
    SAI_OTAI_OA_STAT_INPUT_POWER_TOTAL,

    /**
     * @brief Input power C band
     */
    SAI_OTAI_OA_STAT_INPUT_POWER_C_BAND,

    /**
     * @brief Input power L band
     */
    SAI_OTAI_OA_STAT_INPUT_POWER_L_BAND,

    /**
     * @brief Output power total
     */
    SAI_OTAI_OA_STAT_OUTPUT_POWER_TOTAL,

    /**
     * @brief Output power C band
     */
    SAI_OTAI_OA_STAT_OUTPUT_POWER_C_BAND,

    /**
     * @brief Output power L band
     */
    SAI_OTAI_OA_STAT_OUTPUT_POWER_L_BAND,

    /**
     * @brief Laser bias current
     */
    SAI_OTAI_OA_STAT_LASER_BIAS_CURRENT,

    /**
     * @brief Optical return loss
     */
    SAI_OTAI_OA_STAT_OPTICAL_RETURN_LOSS,

    /**
     * @brief Laser temperature
     */
    SAI_OTAI_OA_STAT_LASER_TEMPERATURE,

    /**
     * @brief Panel input power primary-line rx
     */
    SAI_OTAI_OA_STAT_PANEL_INPUT_POWER_LINEP_RX,

    /**
     * @brief Panel output power primary-line tx
     */
    SAI_OTAI_OA_STAT_PANEL_OUTPUT_POWER_LINEP_TX,

    /**
     * @brief Panel input power secondary-line rx
     */
    SAI_OTAI_OA_STAT_PANEL_INPUT_POWER_LINES_RX,

    /**
     * @brief Panel output power secondary-line tx
     */
    SAI_OTAI_OA_STAT_PANEL_OUTPUT_POWER_LINES_TX,

    /**
     * @brief Laser TEC current
     */
    SAI_OTAI_OA_STAT_LASER_TEC_CURRENT,

    /**
     * @brief Ingress VOA attenuation
     */
    SAI_OTAI_OA_STAT_INGRESS_VOTAI_OA_ATTEN,

    /**
     * @brief Monitor port output power
     */
    SAI_OTAI_OA_STAT_MON_OUTPUT_POWER,

    /**
     * @brief End of statistics
     */
    SAI_OTAI_OA_STAT_END,

} sai_otai_oa_stat_t;

/**
 * @brief Create OA.
 *
 * Allocates and initializes a OA.
 *
 * @param[out] otai_oa_id OA id
 * @param[in] switch_id Switch id on which the OA exists
 * @param[in] attr_count Number of attributes
 * @param[in] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_create_otai_oa_fn)(
        _Out_ sai_object_id_t *otai_oa_id,
        _In_ sai_object_id_t switch_id,
        _In_ uint32_t attr_count,
        _In_ const sai_attribute_t *attr_list);

/**
 * @brief Remove OA
 *
 * @param[in] otai_oa_id OA id
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_remove_otai_oa_fn)(
        _In_ sai_object_id_t otai_oa_id);

/**
 * @brief Set OA attribute
 *
 * @param[in] otai_oa_id OA id
 * @param[in] attr Attribute
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_set_otai_oa_attribute_fn)(
        _In_ sai_object_id_t otai_oa_id,
        _In_ const sai_attribute_t *attr);

/**
 * @brief Get OA attribute
 *
 * @param[in] otai_oa_id OA id
 * @param[in] attr_count Number of attributes
 * @param[inout] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_oa_attribute_fn)(
        _In_ sai_object_id_t otai_oa_id,
        _In_ uint32_t attr_count,
        _Inout_ sai_attribute_t *attr_list);

/**
 * @brief Get OA statistics.
 *
 * @param[in] otai_oa_id OA id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_oa_stats_fn)(
        _In_ sai_object_id_t otai_oa_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _Out_ uint64_t *counters);

/**
 * @brief Get OA statistics extended.
 *
 * @param[in] otai_oa_id OA id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[in] mode Statistics mode
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_oa_stats_ext_fn)(
        _In_ sai_object_id_t otai_oa_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _In_ sai_stats_mode_t mode,
        _Out_ uint64_t *counters);

/**
 * @brief Clear OA statistics counters.
 *
 * @param[in] otai_oa_id OA id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_clear_otai_oa_stats_fn)(
        _In_ sai_object_id_t otai_oa_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids);

/**
 * @brief Routing interface methods table retrieved with sai_api_query()
 */
typedef struct _sai_otai_oa_api_t
{
    sai_create_otai_oa_fn                create_otai_oa;
    sai_remove_otai_oa_fn                remove_otai_oa;
    sai_set_otai_oa_attribute_fn         set_otai_oa_attribute;
    sai_get_otai_oa_attribute_fn         get_otai_oa_attribute;
    sai_get_otai_oa_stats_fn             get_otai_oa_stats;
    sai_get_otai_oa_stats_ext_fn         get_otai_oa_stats_ext;
    sai_clear_otai_oa_stats_fn           clear_otai_oa_stats;
} sai_otai_oa_api_t;

/**
 * @}
 */
#endif /** __SAIEXPERIMENTALOTAIOA_H_ */
