/**
 * Copyright (c) 2014 Microsoft Open Technologies, Inc.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 *    Microsoft would like to thank the following companies for their review and
 *    assistance with these files: Intel Corporation, Mellanox Technologies Ltd,
 *    Dell Products, L.P., Facebook, Inc., Marvell International Ltd.
 *
 * AUTOGENERATED FILE! DO NOT EDIT
 *
 * Copyright (c) 2021 Alibaba Group.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License"); you may
 *    not use this file except in compliance with the License. You may obtain
 *    a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR
 *    CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT
 *    LIMITATION ANY IMPLIED WARRANTIES OR CONDITIONS OF TITLE, FITNESS
 *    FOR A PARTICULAR PURPOSE, MERCHANTABILITY OR NON-INFRINGEMENT.
 *
 *    See the Apache Version 2.0 License for specific language governing
 *    permissions and limitations under the License.
 *
 * @file    saiexperimentalotaiocm.h
 *
 * @brief   This module defines the OCM for the OTAI
 */

#if !defined (__SAIEXPERIMENTALOTAIOCM_H_)
#define __SAIEXPERIMENTALOTAIOCM_H_

#include <saitypes.h>

/**
 * @defgroup SAIEXPERIMENTALOTAIOCM SAI - OTAI OCM specific API definitions
 *
 * @{
 */

/**
 * @brief OCM attribute IDs
 */
typedef enum _sai_otai_ocm_attr_t
{
    /**
     * @brief Start of attributes
     */
    SAI_OTAI_OCM_ATTR_START,

    /**
     * @brief Id
     *
     * @type sai_uint32_t
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
     */
    SAI_OTAI_OCM_ATTR_ID = SAI_OTAI_OCM_ATTR_START,

    /**
     * @brief Scan
     *
     * @type bool
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OCM_ATTR_SCAN,

    /**
     * @brief Frequency granularity in MHz
     *
     * @type sai_uint64_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OCM_ATTR_FREQUENCY_GRANULARITY,

    /**
     * @brief End of attributes
     */
    SAI_OTAI_OCM_ATTR_END,

    /** Custom range base value */
    SAI_OTAI_OCM_ATTR_CUSTOM_RANGE_START = 0x10000000,

    /** End of custom range base */
    SAI_OTAI_OCM_ATTR_CUSTOM_RANGE_END

} sai_otai_ocm_attr_t;

/**
 * @brief OCM stat IDs
 */
typedef enum _sai_otai_ocm_stat_t
{
    /**
     * @brief Start of statistics
     */
    SAI_OTAI_OCM_STAT_START,

    /**
     * @brief A placeholder
     */
    SAI_OTAI_OCM_STAT_NOT_USE = SAI_OTAI_OCM_STAT_START,

    /**
     * @brief End of statistics
     */
    SAI_OTAI_OCM_STAT_END,

} sai_otai_ocm_stat_t;

/**
 * @brief Create OCM.
 *
 * Allocates and initializes a OCM.
 *
 * @param[out] otai_ocm_id OCM id
 * @param[in] switch_id Switch id on which the OCM exists
 * @param[in] attr_count Number of attributes
 * @param[in] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_create_otai_ocm_fn)(
        _Out_ sai_object_id_t *otai_ocm_id,
        _In_ sai_object_id_t switch_id,
        _In_ uint32_t attr_count,
        _In_ const sai_attribute_t *attr_list);

/**
 * @brief Remove OCM
 *
 * @param[in] otai_ocm_id OCM id
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_remove_otai_ocm_fn)(
        _In_ sai_object_id_t otai_ocm_id);

/**
 * @brief Set OCM attribute
 *
 * @param[in] otai_ocm_id OCM id
 * @param[in] attr Attribute
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_set_otai_ocm_attribute_fn)(
        _In_ sai_object_id_t otai_ocm_id,
        _In_ const sai_attribute_t *attr);

/**
 * @brief Get OCM attribute
 *
 * @param[in] otai_ocm_id OCM id
 * @param[in] attr_count Number of attributes
 * @param[inout] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_attribute_fn)(
        _In_ sai_object_id_t otai_ocm_id,
        _In_ uint32_t attr_count,
        _Inout_ sai_attribute_t *attr_list);

/**
 * @brief Get OCM statistics.
 *
 * @param[in] otai_ocm_id OCM id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_stats_fn)(
        _In_ sai_object_id_t otai_ocm_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _Out_ uint64_t *counters);

/**
 * @brief Get OCM statistics extended.
 *
 * @param[in] otai_ocm_id OCM id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[in] mode Statistics mode
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_stats_ext_fn)(
        _In_ sai_object_id_t otai_ocm_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _In_ sai_stats_mode_t mode,
        _Out_ uint64_t *counters);

/**
 * @brief Clear OCM statistics counters.
 *
 * @param[in] otai_ocm_id OCM id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_clear_otai_ocm_stats_fn)(
        _In_ sai_object_id_t otai_ocm_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids);

/**
 * @brief OCM channel attribute IDs
 */
typedef enum _sai_otai_ocm_channel_attr_t
{
    /**
     * @brief Start of attributes
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_START,

    /**
     * @brief Id
     *
     * @type sai_uint32_t
     * @flags MANDATORY_ON_CREATE | CREATE_ONLY
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_ID = SAI_OTAI_OCM_CHANNEL_ATTR_START,

    /**
     * @brief Port
     *
     * @type sai_uint32_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_PORT,

    /**
     * @brief Lower frequency
     *
     * @type sai_uint64_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_LOWER_FREQUENCY,

    /**
     * @brief Upper frequency
     *
     * @type sai_uint64_t
     * @flags CREATE_AND_SET
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_UPPER_FREQUENCY,

    /**
     * @brief End of attributes
     */
    SAI_OTAI_OCM_CHANNEL_ATTR_END,

    /** Custom range base value */
    SAI_OTAI_OCM_CHANNEL_ATTR_CUSTOM_RANGE_START = 0x10000000,

    /** End of custom range base */
    SAI_OTAI_OCM_CHANNEL_ATTR_CUSTOM_RANGE_END

} sai_otai_ocm_channel_attr_t;

/**
 * @brief OCM channel stat IDs
 */
typedef enum _sai_otai_ocm_channel_stat_t
{
    /**
     * @brief Start of statistics
     */
    SAI_OTAI_OCM_CHANNEL_STAT_START,

    /**
     * @brief Channel power
     */
    SAI_OTAI_OCM_CHANNEL_STAT_POWER = SAI_OTAI_OCM_CHANNEL_STAT_START,

    /**
     * @brief End of statistics
     */
    SAI_OTAI_OCM_CHANNEL_STAT_END,

} sai_otai_ocm_channel_stat_t;

/**
 * @brief Create OCM channel.
 *
 * Allocates and initializes a OCM channel.
 *
 * @param[out] otai_ocm_channel_id OCM channel id
 * @param[in] switch_id Switch id on which the OCM exists
 * @param[in] attr_count Number of attributes
 * @param[in] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_create_otai_ocm_channel_fn)(
        _Out_ sai_object_id_t *otai_ocm_channel_id,
        _In_ sai_object_id_t switch_id,
        _In_ uint32_t attr_count,
        _In_ const sai_attribute_t *attr_list);

/**
 * @brief Remove OCM channel
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_remove_otai_ocm_channel_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id);

/**
 * @brief Set OCM channel attribute
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 * @param[in] attr Attribute
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_set_otai_ocm_channel_attribute_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id,
        _In_ const sai_attribute_t *attr);

/**
 * @brief Get OCM channel attribute
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 * @param[in] attr_count Number of attributes
 * @param[inout] attr_list Array of attributes
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_channel_attribute_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id,
        _In_ uint32_t attr_count,
        _Inout_ sai_attribute_t *attr_list);

/**
 * @brief Get OCM channel statistics.
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_channel_stats_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _Out_ uint64_t *counters);

/**
 * @brief Get OCM channel statistics extended.
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 * @param[in] mode Statistics mode
 * @param[out] counters Array of resulting counter values.
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_get_otai_ocm_channel_stats_ext_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids,
        _In_ sai_stats_mode_t mode,
        _Out_ uint64_t *counters);

/**
 * @brief Clear OCM channel statistics counters.
 *
 * @param[in] otai_ocm_channel_id OCM channel id
 * @param[in] number_of_counters Number of counters in the array
 * @param[in] counter_ids Specifies the array of counter ids
 *
 * @return #SAI_STATUS_SUCCESS on success, failure status code on error
 */
typedef sai_status_t (*sai_clear_otai_ocm_channel_stats_fn)(
        _In_ sai_object_id_t otai_ocm_channel_id,
        _In_ uint32_t number_of_counters,
        _In_ const sai_stat_id_t *counter_ids);

/**
 * @brief Routing interface methods table retrieved with sai_api_query()
 */
typedef struct _sai_otai_ocm_api_t
{
    sai_create_otai_ocm_fn                create_otai_ocm;
    sai_remove_otai_ocm_fn                remove_otai_ocm;
    sai_set_otai_ocm_attribute_fn         set_otai_ocm_attribute;
    sai_get_otai_ocm_attribute_fn         get_otai_ocm_attribute;
    sai_get_otai_ocm_stats_fn             get_otai_ocm_stats;
    sai_get_otai_ocm_stats_ext_fn         get_otai_ocm_stats_ext;
    sai_clear_otai_ocm_stats_fn           clear_otai_ocm_stats;

    sai_create_otai_ocm_channel_fn        create_otai_ocm_channel;
    sai_remove_otai_ocm_channel_fn        remove_otai_ocm_channel;
    sai_set_otai_ocm_channel_attribute_fn set_otai_ocm_channel_attribute;
    sai_get_otai_ocm_channel_attribute_fn get_otai_ocm_channel_attribute;
    sai_get_otai_ocm_channel_stats_fn     get_otai_ocm_channel_stats;
    sai_get_otai_ocm_channel_stats_ext_fn get_otai_ocm_channel_stats_ext;
    sai_clear_otai_ocm_channel_stats_fn   clear_otai_ocm_channel_stats;
} sai_otai_ocm_api_t;

/**
 * @}
 */
#endif /** __SAIEXPERIMENTALOTAIOCM_H_ */
